# This file is covered by the LICENSE file in the root of this project.
labels: 
  0 : "unlabeled"
  1 : "outlier"
  10: "car"
  11: "bicycle"
  13: "bus"
  15: "motorcycle"
  16: "on-rails"
  18: "truck"
  20: "other-vehicle"
  30: "person"
  31: "bicyclist"
  32: "motorcyclist"
  40: "road"
  44: "parking"
  48: "sidewalk"
  49: "other-ground"
  50: "building"
  51: "fence"
  52: "other-structure"
  60: "lane-marking"
  70: "vegetation"
  71: "trunk"
  72: "terrain"
  80: "pole"
  81: "traffic-sign"
  99: "other-object"
  252: "moving-car"
  253: "moving-bicyclist"
  254: "moving-person"
  255: "moving-motorcyclist"
  256: "moving-on-rails"
  257: "moving-bus"
  258: "moving-truck"
  259: "moving-other-vehicle"

color_map: # bgr
  0 : [0, 0, 0]
  1 : [0, 0, 255]
  10: [245, 150, 100]
  11: [245, 230, 100]
  13: [250, 80, 100]
  15: [150, 60, 30]
  16: [255, 0, 0]
  18: [180, 30, 80]
  20: [255, 0, 0]
  30: [30, 30, 255]
  31: [200, 40, 255]
  32: [90, 30, 150]
  40: [255, 0, 255]
  44: [255, 150, 255]
  48: [75, 0, 75]
  49: [75, 0, 175]
  50: [0, 200, 255]
  51: [50, 120, 255]
  52: [0, 150, 255]
  60: [170, 255, 150]
  70: [0, 175, 0]
  71: [0, 60, 135]
  72: [80, 240, 150]
  80: [150, 240, 255]
  81: [0, 0, 255]
  99: [255, 255, 50]
  252: [245, 150, 100]
  256: [255, 0, 0]
  253: [200, 40, 255]
  254: [30, 30, 255]
  255: [90, 30, 150]
  257: [250, 80, 100]
  258: [180, 30, 80]
  259: [255, 0, 0]
content: # as a ratio with the total number of points
  0: 0.018889854628292943
  1: 0.0002937197336781505
  10: 0.040818519255974316
  11: 0.00016609538710764618
  13: 2.7879693665067774e-05
  15: 0.00039838616015114444
  16: 0.0
  18: 0.0020633612104619787
  20: 0.0016218197275284021
  30: 0.00017698551338515307
  31: 1.1065903904919655e-08
  32: 5.532951952459828e-09
  40: 0.1987493871255525
  44: 0.014717169549888214
  48: 0.14392298360372
  49: 0.0039048553037472045
  50: 0.1326861944777486
  51: 0.0723592229456223
  52: 0.002395131480328884
  60: 4.7084144280367186e-05
  70: 0.26681502148037506
  71: 0.006035012012626033
  72: 0.07814222006271769
  80: 0.002855498193863172
  81: 0.0006155958086189918
  99: 0.009923127583046915
  252: 0.001789309418528068
  253: 0.00012709999297008662
  254: 0.00016059776092534436
  255: 3.745553104802113e-05
  256: 0.0
  257: 0.00011351574470342043
  258: 0.00010157861367183268
  259: 4.3840131989471124e-05
# classes that are indistinguishable from single scan or inconsistent in
# ground truth are mapped to their closest equivalent
learning_map:
  0 : 255     # "unlabeled"
  1 : 255    # "outlier" mapped to "unlabeled" --------------------------mapped
  10: 11     # "car"
  11: 12    # "bicycle"
  13: 15     # "bus" mapped to "other-vehicle" --------------------------mapped
  15: 13     # "motorcycle"
  16: 15     # "on-rails" mapped to "other-vehicle" ---------------------mapped
  18: 14     # "truck"
  20: 15     # "other-vehicle"
  30: 16     # "person"
  31: 17     # "bicyclist"
  32: 18     # "motorcyclist"
  40: 0    # "road"
  44: 1    # "parking"
  48: 2    # "sidewalk"
  49: 3    # "other-ground"
  50: 4    # "building"
  51: 5    # "fence"
  52: 255     # "other-structure" mapped to "unlabeled" ------------------mapped
  60: 0     # "lane-marking" to "road" ---------------------------------mapped
  70: 6    # "vegetation"
  71: 7    # "trunk"
  72: 8    # "terrain"
  80: 9    # "pole"
  81: 10    # "traffic-sign"
  99: 255     # "other-object" to "unlabeled" ----------------------------mapped
  252: 11    # "moving-car"
  253: 17    # "moving-bicyclist"
  254: 16    # "moving-person"
  255: 18    # "moving-motorcyclist"
  256: 15    # "moving-on-rails" mapped to "moving-other-vehicle" ------mapped
  257: 15    # "moving-bus" mapped to "moving-other-vehicle" -----------mapped
  258: 14    # "moving-truck"
  259: 15    # "moving-other-vehicle"
learning_map_inv: # inverse of previous map
  255: 0      # "unlabeled", and others ignored
  11: 10     # "car"
  12: 11     # "bicycle"
  13: 15     # "motorcycle"
  14: 18     # "truck"
  15: 20     # "other-vehicle"
  16: 30     # "person"
  17: 31     # "bicyclist"
  18: 32     # "motorcyclist"
  0: 40     # "road"
  1: 44    # "parking"
  2: 48    # "sidewalk"
  3: 49    # "other-ground"
  4: 50    # "building"
  5: 51    # "fence"
  6: 70    # "vegetation"
  7: 71    # "trunk"
  8: 72    # "terrain"
  9: 80    # "pole"
  10: 81    # "traffic-sign"
learning_ignore: # Ignore classes
  255: True      # "unlabeled", and others ignored
  11: False     # "car"
  12: False     # "bicycle"
  13: False     # "motorcycle"
  14: False     # "truck"
  15: False     # "other-vehicle"
  16: False     # "person"
  17: False     # "bicyclist"
  18: False     # "motorcyclist"
  0: False     # "road"
  1: False    # "parking"
  2: False    # "sidewalk"
  3: False    # "other-ground"
  4: False    # "building"
  5: False    # "fence"
  6: False    # "vegetation"
  7: False    # "trunk"
  8: False    # "terrain"
  9: False    # "pole"
  10: False    # "traffic-sign"

instances: # classes with instances
  255: False      # "unlabeled", and others ignored
  11: True     # "car"
  12: True     # "bicycle"
  13: True     # "motorcycle"
  14: True     # "truck"
  15: True     # "other-vehicle"
  16: True     # "person"
  17: True     # "bicyclist"
  18: True     # "motorcyclist"
  0: False     # "road"
  1: False    # "parking"
  2: False    # "sidewalk"
  3: False    # "other-ground"
  4: False    # "building"
  5: False    # "fence"
  6: False    # "vegetation"
  7: False    # "trunk"
  8: False    # "terrain"
  9: False    # "pole"
  10: False    # "traffic-sign"
  
split: # sequence numbers
  train:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 9
    - 10
  valid:
    - 8
sensor:
    name: "HDL64"
    type: "spherical" # projective
    fov_up: 3
    fov_down: -25 
    img_prop:
      width: 1024
      height: 64
    img_means: #range,x,y,z,signal
      - 12.12
      - 10.88
      - 0.23
      - -1.04
      - 0.21
    img_stds: #range,x,y,z,signal
      - 12.32
      - 11.47
      - 6.91
      - 0.86
      - 0.16
